sudo: required
dist: trusty
os:
  - linux
language: java
jdk: oraclejdk8
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install lmdb; fi
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  email:
    - ben.alex@acegi.com.au
    - stoffe@gmail.com
