sudo: required
dist: trusty
os:
  - linux
  - osx
language: java
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt-cache search lmdb; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq liblmdb-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install lmdb; fi
jdk:
  - oraclejdk8
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  email:
    - ben.alex@acegi.com.au
    - stoffe@gmail.com
