version: '{build}'

image: Visual Studio 2015

clone_depth: 50

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk9"
  MVN_VER: 3.6.0
  PYTHON: "C:\\Python35"

cache:
  - C:\Users\appveyor\apache-maven-%MVN_VER% -> appveyor.yml
  - C:\Users\appveyor\.m2 -> pom.xml

install:
  - if not exist C:\Users\appveyor\apache-maven-%MVN_VER% (
      curl -LsS "http://www.apache.org/dyn/closer.cgi?action=download&filename=maven/maven-3/%MVN_VER%/binaries/apache-maven-%MVN_VER%-bin.zip" > apache-maven.zip &&
      unzip apache-maven.zip -d C:\Users\appveyor
    )
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\Users\appveyor\apache-maven-%MVN_VER%\bin;%PATH%
  - pip install codecov

build_script:
  - mvn -V -B --settings .travis-settings.xml -e verify
  - codecov -X gcov -f target/site/jacoco/jacoco.xml

notifications:
  - provider: Email
    to:
      - ben.alex@acegi.com.au
      - stoffe@gmail.com
    on_build_success: false
